/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.slyver.ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.slyver.db.LoginDb;
import org.slyver.runtime.MainScreen;

/**
 *
 * @author Andres
 */
public class MainScreenUI extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     * @throws java.sql.SQLException
     */
    
    FilterUI FormFilter = new FilterUI();
    
    public MainScreenUI() throws SQLException {
        initComponents();
        new MainScreen().ReportsLists();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReportsList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        dynamicTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        SaveReport = new javax.swing.JButton();
        RepUpdate = new javax.swing.JButton();
        filterWindow = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        adminUI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReportsList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        ReportsList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ReportsListItemStateChanged(evt);
            }
        });
        ReportsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsListActionPerformed(evt);
            }
        });

        dynamicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dynamicTable);

        jLabel2.setText("Seleccionar Reporte");

        SaveReport.setText("Guardar Datos");
        SaveReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveReportActionPerformed(evt);
            }
        });

        RepUpdate.setText("Actualizar");
        RepUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepUpdateActionPerformed(evt);
            }
        });

        filterWindow.setText("Filtrar Contendo");
        filterWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterWindowActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        adminUI.setText("Administracion");
        adminUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUIActionPerformed(evt);
            }
        });
        jMenu1.add(adminUI);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(ReportsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RepUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveReport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportsList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(RepUpdate)
                    .addComponent(filterWindow)
                    .addComponent(SaveReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUIActionPerformed
        try {
            // TODO add your handling code here:
            if(LoginDb.userlvl == 1){
              new StructureAdminUI().setVisible(true);  
            }else{
                JOptionPane.showMessageDialog(null, "No tiene los permisos para esta opcion", "Aviso", 1);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminUIActionPerformed

    private void ReportsListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ReportsListItemStateChanged
        try {
            // TODO add your handling code here:
            new MainScreen().DynmicTable(ReportsList.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReportsListItemStateChanged

    private void SaveReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReportActionPerformed
        try {
            // TODO add your handling code here:
            new MainScreen().SaveTableData(ReportsList.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveReportActionPerformed

    private void RepUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepUpdateActionPerformed
        try {
            // TODO add your handling code here:
            
            new MainScreen().ReportsLists();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MainScreenUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RepUpdateActionPerformed

    private void ReportsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportsListActionPerformed

    private void filterWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterWindowActionPerformed
        // TODO add your handling code here:
        FormFilter.setVisible(true);
    }//GEN-LAST:event_filterWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainScreenUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainScreenUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RepUpdate;
    public static javax.swing.JComboBox ReportsList;
    private javax.swing.JButton SaveReport;
    private javax.swing.JMenuItem adminUI;
    public static javax.swing.JTable dynamicTable;
    private javax.swing.JButton filterWindow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
